### ISSUE TITLE
Line numbers in errors are not useful

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#9]
UPDATE 08/12:
This PR may fix the root cause in jpy jpy-consortium/jpy/pull/158

UPDATE 07/16: I think [#39 Expose python code errors as diagnostics](https://github.com/deephaven/vscode-deephaven/issues/39)  should address the user experience challenge on this one. It won't help with the `-1` line numbers which seems likely to be a Python runtime bug (see https://github.com/python/cpython/issues/101400 for an example).

I run this code with a known error on line 11.
```python

from deephaven import empty_table, time_table
from deephaven.plot import Figure

t1 = empty_table(10).update(["X = i", "Y = 10 * i"])
t2 = time_table("PT1s").update(["X = i%10", "Y = 10 * i"])

t3 = t1.natural_join(t2.last_by("X"), on="X", joins="YY=Y")

p1 = Figure().plot_xy("Plot 1", t1, x="X", y="Y").show()
p2 = Figure().plot_xy(t2, "X", "Y").show()

# p1 = Figure().plot_xy("Plot 1", t1, x="X", y="Y").show()
# p2 = Figure().plot_xy("Plot 2", t2, x="X", y="Y").show()


print("DH Rules")
print("DH Sucks")
```

Here is the error -- no mention of line 11 or even the file name:
```
14:16:33.055 ERROR r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: Improper input type: name=series_name type=<class 'deephaven.table.Table'> supported=['str'] : Improper input type: name=series_name type=<class 'deephaven.table.Table'> supported=['str']
NoneType: None

Line: 47
Namespace: _assert_type
File: /private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/plot/figure.py
Traceback (most recent call last):
  File "<string>", line -1, in <module>
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/plot/figure.py", line -1, in plot_xy
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/plot/figure.py", line -1, in _convert_j
  File "/private/tmp/my-dh-venv/lib/python3.11/site-packages/deephaven/plot/figure.py", line -1, in _assert_type

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:205)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:205)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:165)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:165)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:72)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:75)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:193)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1537)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:995)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:100)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by bmingles** [comment]
Oddly when I run this script, I get the same error with different line numbers.

**Running full script:**
<img width="1543" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/e01af20d-cf6d-463f-8338-b9035c119c36">

**Running selected line 10 `p2 = Figure().plot_xy(t2, "X", "Y").show()`**
<img width="1546" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/681e8ecb-9845-42eb-9955-ec1747549e24">

I'm not sure how to get the `-1` line number showed in the ticket description. @chipkent curious if I'm doing something wrong for the reproduction here?

That said, even if the line number is positive, there are 2 issues I see here:
1. The line number seems to be relative to the number of selected lines as opposed to the file
2. It just says `<string>` instead of providing a file name.

I do actually see this same behavior in code studio, so I think this is something that we should create a ticket for there and address there as well. The line number issue is likely something we can address only there and get it for free in the extension. The filename may be more nuanced since vscode file could be something outside of what code studio is aware of and would need special handling.

**Comment by bmingles** [comment]
@chipkent there's a possibility the `-1` line numbers may be a Python bug fixed in `3.12`.

**Comment by chipkent** [comment]
I am on python `3.12` and am still getting `-1` line numbers.

<img width="905" alt="image" src="https://github.com/user-attachments/assets/702b8754-a283-4b02-b23f-dc7c6bf5c87f">

**Comment by chipkent** [comment]
Actually, looking at that, there is a `Line: 20` in there that is correct.  The `line -1` is in the traceback.  Maybe this is ok.

**Comment by chipkent** [comment]
I'm reopening this.  The problem is real.

```python
import sys; print(sys.version)

from deephaven import empty_table, time_table
from deephaven.plot import Figure

t1 = empty_table(10).update(["X = i", "Y = 10 * i"])
t2 = time_table("PT1s").update(["X = i%10", "Y = 10 * i"])

t3 = t1.natural_join(t2.last_by("X"), on="X", joins="YY=Y")

p1 = Figure().plot_xy("Plot 1", t1, x="X", y="Y").show()
p2 = Figure().plot_xy(t2, "X", "Y").show()

# p1 = Figure().plot_xy("Plot 1", t1, x="X", y="Y").show()
# p2 = Figure().plot_xy("Plot 2", t2, x="X", y="Y").show()


print("DH Rules")
print("DH Sucks")

# import mymod
```

```
12:16:59.955 ERROR r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: Improper input type: name=series_name type=<class 'deephaven.table.Table'> supported=['str'] : Improper input type: name=series_name type=<class 'deephaven.table.Table'> supported=['str']
NoneType: None

Line: 47
Namespace: _assert_type
File: /private/tmp/my-dh-venv/lib/python3.12/site-packages/deephaven/plot/figure.py
Traceback (most recent call last):
  File "<string>", line -1, in <module>
  File "/private/tmp/my-dh-venv/lib/python3.12/site-packages/deephaven/plot/figure.py", line -1, in plot_xy
  File "/private/tmp/my-dh-venv/lib/python3.12/site-packages/deephaven/plot/figure.py", line -1, in _convert_j
  File "/private/tmp/my-dh-venv/lib/python3.12/site-packages/deephaven/plot/figure.py", line -1, in _assert_type
```

Note here that the problem is in the creation of `p2`.  a value of the wrong type is passed into `plot_xy`.  The stack trace here is totally unuseful because the original line is noted as `File "<string>", line -1, in <module>`.  The `-1` line number does not help the user resolve the location of the problem.

**Comment by chipkent** [comment]
Note that the above has `Line 47` as the problem when it is in fact line 13.

**Comment by bmingles** [comment]
It looks like line `47` is referring to where the error gets raised inside of `figure.py`
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/098d7da2-c5ca-4c28-9631-ada370da7a0a">

The `-1` line numbers are still a bug for the `File "<string>"` aka. the string content of the script that is being passed to DH.

**Comment by chipkent** [comment]
I have now done a `pip` installed DH on python 3.12, and I still see the `-1` line numbers.

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/1beffa9c-618b-4e8a-9bac-921a6d031e12">

**Comment by jmao-denver** [comment]
Fixed by https://github.com/jpy-consortium/jpy/pull/158
